### ISSUE TITLE
Cannot build android app with SDK Version 3.3.2

### ISSUE THREAD

**Issue by sheriffmarley** [bugfender/rn-bugfender#83]
Hi there,

today you released a new Bugfender version 3.3.2 in your sdk repository. This breaks 
`> Task :app:checkStagingDebugAarMetadata FAILED` since the `.aar` files are missing.

```

> Task :app:checkStagingDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkStagingDebugAarMetadata'.
> Could not resolve all files for configuration ':app:stagingDebugRuntimeClasspath'.
   > Failed to transform android-3.3.2.aar (com.bugfender.sdk:android:3.3.2) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find android-3.3.2.aar (com.bugfender.sdk:android:3.3.2).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/bugfender/sdk/android/3.3.2/android-3.3.2.aar
            https://repo.maven.apache.org/maven2/com/bugfender/sdk/android/3.3.2/android-3.3.2.jar

```

Hope you fix this issue asap.

Thanks in advance

**Comment by jgimenez** [comment]
Hi there,
As you mentioned, the maven package for version 3.3.2 released yesterday was malformed and was missing the .aar file.
Our engineers released version 3.3.3 with the corrected package a few minutes ago.
Please try rebuilding your project, and that should fix the problems you are experiencing. If you keep experiencing any issues, please let me know so we can look into it.

**Comment by BinhTNT** [comment]
Hello,
I got the same issue. I've tried to rebuild but it's still experiencing it. We're using rn-bugfender v2.2.1.

**Comment by sheriffmarley** [comment]
> Hello, I got the same issue. I've tried to rebuild but I'm still experiencing it. We're using rn-bugfender v2.2.1.

You need to clear the cache:

https://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies

**Comment by BinhTNT** [comment]
@sheriffmarley It works now. Thanks for your help !
